version: "3.11"

services:
  auth_service:
    build: ./auth_service/
    command: npm start
    restart: always
    ports:
      - "8000:5000"

  notes_service:
    build: ./notes_service/
    command: npm start
    restart: always
    ports:
      - 8001:5000
